apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  # Random schedule: From Mon to Fri every week at 23:45
  schedule: "45 23 * * 0-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: http-request-container
            image: stion/easy-http-client:0.0.1
          restartPolicy: OnFailure