apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "45 23 * * 0-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: http-request-container
            image: stion/easy-http-client:0.0.2
            env:
            - name: REQUESTS
              value: '{"url": "https://example.com", "method": "GET"}'
          restartPolicy: OnFailure