name: Build, Push Docker image using deployment tag, Sync ArgoCD application

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract image tag from deployment
      id: extract_tag
      run: |
        IMAGE_TAG=$(grep 'image:' ./.kube/cronjob.test.yaml | awk -F: '{print $3}' | tr -d ' "')
        echo "Extracted image tag is $IMAGE_TAG"
        echo "::set-output name=image_tag::$IMAGE_TAG"

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/easy-http-client:${{ steps.extract_tag.outputs.image_tag }}
    - name: Build and push Docker image Latest
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/easy-http-client:latest